GET http://localhost:8080/api/books
Accept: application/json
###

GET http://localhost:8080/api/authors
Accept: application/json
###

GET http://localhost:8080/api/experts
Accept: application/json
###

GET http://localhost:8080/api/lectures
Accept: application/json
###

GET http://localhost:8080/api/courses
Accept: application/json
###

GET http://localhost:8080/api/smartwatch
Accept: application/json
###

GET http://localhost:8080/api/xbox
Accept: application/json
###

GET http://localhost:8080/api/tv
Accept: application/json

--WebAppBoundary
Content-Disposition: form-data; name="file"; filename="pom.xml"

< ./pom.xml
--WebAppBoundary--

